apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
spec:
  accessModes:
    - ReadWriteOnce # 1 инстанс может использовать только 1 pvc
# ReadWriteMany - Несколько инстансов могут писать и читать
# ReadOnlyMany - Несколько инстансов могут читать
  resources:
    requests:
      storage: 1Gi