apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.convApp.name }}_svc"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.convApp.port }}
  selector:
    components: {{ .Values.convApp.components }}