apiVersion: v1
kind: Service
metadata:
  name: svc-conv-app
spec:
  type: NodePort
  ports:
    - port: 3000 # адрес порта доступный внутри кластера для других подов
      targetPort: 80
      nodePort: 31119
  selector:
    app: conv-app

