apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      components: convenrter
  template:
    metadata:
      labels:
        components: convenrter
    spec:
      containers:
      - name: convenrter
        image: antonlarichev/conv-service:1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "1024Mi"
        env:
          - name: AMQP_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: secret-rabbitmq
                key: AMQP_HOSTNAME
          - name: AMQP_USER
            valueFrom:
              secretKeyRef:
                name: secret-rabbitmq
                key: AMQP_USER
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-rabbitmq
                key: AMQP_PASSWORD
          - name: AMQP_EXCHANGE
            valueFrom:
              secretKeyRef:
                name: secret-rabbitmq
                key: AMQP_EXCHANGE
          - name: AMQP_QUEUE
            valueFrom:
              secretKeyRef:
                name: secret-rabbitmq
                key: AMQP_QUEUE
          - name: VITE_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: converter-cm
                key: VITE_DOMAIN