apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data: 
  key: {{ .Release.Name }}
  name: {{ .Values.app.name | upper | quote }}
  chart: {{ quote .Chart.AppVersion }}
  date: {{ now | date "2006-01-02" | quote }}