apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.app.name }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
  selector:
    components: {{ .Values.app.components }}