apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.api.name }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.api.port }}
  selector:
    components: {{ .Values.api.components }}